site_name: Javascript Mini Projects
nav:
  - Start Here: index.md
  - Speech Recognition: 1-speech-recognition.md
  - Canvas Checkboard: 2-checkerboard-canvas.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages: ['lua', 'javascript', 'python', 'swift']
extra_css:
  - css/style.css
